### ISSUE TITLE
控制台提示隐藏成功，本地搜索引擎也搜索不到了，但首页仍显示

### ISSUE THREAD

**Issue by BSDxxxx** [printempw/hexo-hide-posts#10]
本来怀疑是和hexo-generator-index-plus排序插件冲突了，但是卸载排序插件，clean后依旧未解决

**Comment by printempw** [comment]
有安装其他什么插件吗？方便的话提供一下 `hexo -v` 的输出以及插件列表

**Comment by BSDxxxx** [comment]
F:\ProgramFiles\GitHub\MyBlog>hexo -v
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.17134 win32 x64
node: 12.14.1
v8: 7.7.299.13-node.16
uv: 1.33.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019c
unicode: 12.1

插件列表有什么方便的查询方式吗...

**Comment by BSDxxxx** [comment]
[hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md)

[index-generator-plus](https://github.com/YuyingWu/hexo-generator-index-plus)

[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)

[hexo-git-backup](https://github.com/coneycode/hexo-git-backup)

[hexo-deployer-git](https://github.com/hexojs/hexo-deployer-git)

[hexo-generator-searchdb](https://github.com/theme-next/hexo-generator-searchdb)
主要就是这些了

**Comment by printempw** [comment]
嗯……我这边试了一下，没法复现。

文章还在首页的话，存档页、标签页等页面上也有吗？本插件的配置有没有修改过

**Comment by BSDxxxx** [comment]
@printempw 我又看了一遍readme，发现问题了。。。
public_generators这个参数我理解错了，看成是指定需要隐藏的generator了
